listeDeTrams
tramway* listeDeTrams::d_tete
int listeDeTrams::d_nombreDeTrams
listeDeTrams::listeDeTrams()
Le constructeur
listeDeTrams::~listeDeTrams()
DESTRUCTEUR.
References tramway::suivant.
void listeDeTrams::ajoutEnTete(int numero, int vitesseMax, bool sens, double posX, double posY, ligne *ligneAffect)
AJOUTS.
numLigne - vitesseMax - sens - posX - posY - ligneAffect -
References tramway::suivant.
Referenced by ajoutAuCorps.
void listeDeTrams::ajoutAuQueue(int numero, int vitesseMax, bool sens, double posX, double posY, ligne *ligneAffect)
numLigne - vitesseMax - sens - posX - posY - ligneAffect -
References tramway::suivant.
Referenced by ajoutAuCorps.
void listeDeTrams::ajoutAuCorps(int numero, int vitesseMax, bool sens, double posX, double posY, ligne *ligneAffect, int corps)
numLigne - vitesseMax - sens - posX - posY - corps - ligneAffect -
References ajoutEnTete, ajoutAuQueue, tramway::suivant.
void listeDeTrams::supprEnTete()
SUPPRESSIONS.
delete en tete
References tramway::suivant.
Referenced by supprAuCorps.
void listeDeTrams::supprAuQueue()
delete au queue
References tramway::suivant.
Referenced by supprAuCorps.
void listeDeTrams::supprAuCorps(int corps)
delete a une position int corps
References supprEnTete, supprAuQueue, tramway::suivant.
tramway * listeDeTrams::accesEnTete() const
ACCES.
- le premier tram de la liste
tramway * listeDeTrams::accesAuQueue() const
- le dernier tram de la liste
References tramway::suivant.
tramway * listeDeTrams::accesAuCorps(int corps) const
- le corps ieme tram de la liste
References tramway::suivant.
Referenced by tracer::placerTrams, tracer::moveTrams.
void listeDeTrams::afficherListe() const
Affiche la liste tram au niveau console
References tramway::numLigne, tramway::suivant.
bool listeDeTrams::estVide() const
- si le nombre tram =0
int listeDeTrams::nombreDeTrams() const
- le nombre tram
Referenced by tracer::placerTrams, tracer::moveTrams.