ligne
int ligne::d_numDeLigne
std::string ligne::d_nomDeLigne
double ligne::d_distanceEntreArrets
listeArrets* ligne::d_arrets
listeDeTrams* ligne::d_trams
ligne::ligne()
Constructeur par default.
ligne::ligne(int numDeLigne, std::string nomDeLigne, double distanceEntreArrets, listeArrets *arrets, listeDeTrams *trams)
Constructeur par défaut numLigne - numero de ligne nomLigne - nom de ligne arrets - liste des arrets trams - listes des trams distanceArret - distance entre chaque arret
References nomDeLigne, distanceEntreArrets, arrets, trams.
ligne::ligne(ligne *ligne_a_Creer)
Constructeur par ligne maligne - ligne à crée
References nomDeLigne, numDeLigne, arrets, trams, distanceEntreArrets.
std::string ligne::nomDeLigne() const
Methodes Accés
- retourne le nom de la ligne
Referenced by ligne, nomDeLigne.
int ligne::numDeLigne() const
- retourne le numero de la ligne
Referenced by ligne, numDeLigne, tracer::liensArrets.
listeArrets * ligne::arrets() const
- return un private d_arrets
Referenced by ligne, arrets, tracer::placerArrets, tracer::liensArrets, tracer::moveTram.
listeDeTrams * ligne::trams() const
- return un private d_trams
Referenced by ligne, trams, tracer::placerTrams, tracer::moveTrams.
double ligne::distanceEntreArrets() const
- return un private d_distanceEntrArrets
Referenced by ligne, distanceEntreArrets.
void ligne::nomDeLigne(std::string nomDeLigne)
Methodes de modification.
nomLigne - nom de ligne
References nomDeLigne.
void ligne::numDeLigne(int numDeLigne)
numDeLigne - numero de ligne
References numDeLigne.
void ligne::arrets(listeArrets *arrets)
arrets - liste des arrets
References arrets.
void ligne::trams(listeDeTrams *trams)
trams - liste de trams
References trams.
void ligne::distanceEntreArrets(double distanceEntreArrets)
distanceEntreArrets - distance entre les arrets
References distanceEntreArrets.
ligne::~ligne()
Destructeur.