listeArrets
arret* listeArrets::d_tete
int listeArrets::d_nombreArrets
listeArrets::listeArrets()
Constructeur.
void listeArrets::ajoutEnTete(double posX, double posY, int tempsArret, std::string nomArret)
AJOUTS.
posX - posY - tempsArret - nomArret -
References arret::prochainArret.
Referenced by ajoutAuCorps.
void listeArrets::ajoutAuCorps(double posX, double posY, int tempsArret, std::string nomArret, int corps)
posX - posY - tempsArret - nomArret - corsp - la position
References ajoutEnTete, ajoutAuQueue, arret::prochainArret.
void listeArrets::ajoutAuQueue(double posX, double posY, int tempsArret, std::string nomArret)
AJOUTS.
posX - posY - tempsArret - nomArret -
References arret::prochainArret.
Referenced by ajoutAuCorps.
void listeArrets::supprEnTete()
SUPPRIMER.
SUPPRESSION.Delete en tete
References arret::prochainArret.
Referenced by supprAuCorps.
void listeArrets::supprAuCorps(int corps)
- corps -supprimer a une position
References supprEnTete, supprAuQueue, arret::prochainArret.
void listeArrets::supprAuQueue()
delete au queue
References arret::prochainArret.
Referenced by supprAuCorps.
arret * listeArrets::accesEnTete() const
ACCES.
- le premier arret
Referenced by tracer::moveTram.
arret * listeArrets::accesAuCorps(int corps) const
- corps - a une position
References arret::prochainArret.
Referenced by tracer::placerArrets, tracer::liensArrets.
arret * listeArrets::accesAuQueue() const
- retourne le dernier arret
References arret::prochainArret.
void listeArrets::afficherListe() const
Affiche la liste des arrets au niveau console.
References arret::nomArret, arret::prochainArret.
bool listeArrets::estAucunArret() const
- si le nombre arret est vide
int listeArrets::nombreArrets() const
- le nombre d'arrets
Referenced by tracer::placerArrets, tracer::liensArrets.
listeArrets::~listeArrets()
Destructeur.
DESTRUCTEUR.
References arret::prochainArret.